<a href="https://colab.research.google.com/github/Abeeraiftikhar/AI-DrugDiscovery-QSAR-BRCA1/blob/main/chembl_data_curation_BRCA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **AI and Drug Discovery : QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

## **Target Selection: BRCA1**

BRCA1 (Breast Cancer Type 1 Susceptibility Protein) was selected as the molecular target for this assignment due to its significant role in DNA damage repair and its strong clinical relevance in breast and ovarian cancer research.

Bioactivity data associated with BRCA1 were retrieved from the ChEMBL database and evaluated for QSAR analysis. A total of five IC50 bioactivity records were identified. Although the dataset size is limited, it was curated and analyzed for educational and methodological demonstration of QSAR data retrieval and preprocessing steps.

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [1]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

ValueError: mount failed

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [2]:
! mkdir "/content/gdrive/Colab Notebooks /data"

mkdir: cannot create directory ‘/content/gdrive/Colab Notebooks /data’: No such file or directory

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [3]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 2.1 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 5.6 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 6.3 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [4]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Step 1: Search for Traget Protein

## **Target Identification (BRCA1)**
Search ChEMBL for the BRCA1 target and select the most relevant entry.

In [10]:
target = new_client.target
target_query = target.search("BRCA1")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Breast cancer type 1 susceptibility protein,19.0,False,CHEMBL5990,"[{'accession': 'P38398', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,Lys-63-specific deubiquitinase BRCC36,19.0,False,CHEMBL4105965,"[{'accession': 'P46736', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Homo sapiens,BRCA1-associated protein,18.0,False,CHEMBL5291566,"[{'accession': 'Q7Z569', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Ubiquitin carboxyl-terminal hydrolase BAP1,15.0,False,CHEMBL1293314,"[{'accession': 'Q92560', 'component_descriptio...",SINGLE PROTEIN,9606

**Reterive Bioactivity data for selected target**

In [11]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL5990'

**Now retrieve only bioactivity data for target; **GTPase KRas(CHEMBL2189121)** with reported IC 50  values in nM (nanomolar) unit.**

In [12]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [13]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6222842,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,4.6
1,None,None,6222843,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
2,None,None,6222844,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,52.8
3,None,None,6222845,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
4,None,None,6222846,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,15.0

In [14]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [15]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in foler "data"**

In [16]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

cp: cannot create regular file '/content/gdrive/My Drive/Colab Notebooks/data': No such file or directory

In [17]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

ls: cannot access '/content/gdrive/My Drive/Colab Notebooks/data': No such file or directory

In [18]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,6222842,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)C(N)=O)[C@@H](C)O,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '9.34', 'le': '0.19', 'lle': '7.67', 'sei': '2.25'}",CHEMBL1784774,,CHEMBL1784774,5.34,0,http://www.openphacts.org/units/Nanomolar,1429759,=,1,1,=,,IC50,nM,,4600.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,4.6
,,6222843,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](CCC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)C(N)=O)[C@@H](C)O,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1781980,J Med Chem,2011,,CHEMBL1784771,,CHEMBL1784771,,0,http://www.openphacts.org/units/Nanomolar,1429756,>,1,1,>,,IC50,nM,,250000.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,250.0
,,6222844,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](CC(C(=O)O)C(=O)O)C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)C(N)=O)[C@@H](C)O,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '7.41', 'le': '0.14', 'lle': '6.54', 'sei': '1.74'}",CHEMBL1784772,,CHEMBL1784772,4.28,0,http://www.openphacts.org/units/Nanomolar,1429757,=,1,1,=,,IC50,nM,,52800.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,52.8
,,6222845,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)C(N)=O)[C@@H](C)O)[C@@H](C)OP(=O)(O)O,Outside typical range,"Values for this activity type are unusually large/small, so may not be accurate",CHEMBL1781980,J Med Chem,2011,,CHEMBL1784773,,CHEMBL1784773,,0,http://www.openphacts.org/units/Nanomolar,1429758,>,1,1,>,,IC50,nM,,250000.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,250.0
,,6222846,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N[C@@H](C)C(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)C(N)=O)[C@@H](C)O,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '8.84', 'le': '0.18', 'lle': '7.64', 'sei': '1.96'}",CHEMBL1784704,,CHEMBL1784704,4.82,0,http://www.openphacts.org/units/Nanomolar,1429673,=,1,1,=,,IC50,nM,,15000.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,15.0
,,6222847,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O)N[C@@H](C)C(=O)N[C@@H](Cc1ccccc1)C(N)=O,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '8.23', 'le': '0.16', 'lle': '6.15', 'sei': '2.05'}",CHEMBL1784770,,CHEMBL1784770,4.46,0,http://www.openphacts.org/units/Nanomolar,1429755,=,1,1,=,,IC50,nM,,35000.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,35.0
,,6222848,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)N[C@@H](Cc1ccccc1)C(N)=O)C(C)C,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '9.65', 'le': '0.19', 'lle': '6.54', 'sei': '2.53'}",CHEMBL1784703,,CHEMBL1784703,5.50,0,http://www.openphacts.org/units/Nanomolar,1429672,=,1,1,=,,IC50,nM,,3200.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,3.2
,,6222849,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O)N[C@@H](CO)C(=O)N[C@@H](Cc1ccccc1)C(N)=O,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '8.11', 'le': '0.16', 'lle': '7.24', 'sei': '1.90'}",CHEMBL1784775,,CHEMBL1784775,4.52,0,http://www.openphacts.org/units/Nanomolar,1429760,=,1,1,=,,IC50,nM,,30100.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,30.1
,,6222850,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarization assay,B,,,BAO_0000190,BAO_0000357,single protein format,CC[C@H](C)[C@H](NC(=O)[C@@H]1CCCN1C(=O)[C@H](COP(=O)(O)O)NC(C)=O)C(=O)N[C@@H](Cc1ccccc1)C(N)=O,,,CHEMBL1781980,J Med Chem,2011,"{'bei': '8.82', 'le': '0.18', 'lle': '5.81', 'sei': '2.37'}",CHEMBL1784776,,CHEMBL1784776,5.15,0,http://www.openphacts.org/units/Nanomolar,1429761,=,1,1,=,,IC50,nM,,7100.0,CHEMBL5990,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,,,IC50,uM,UO_0000065,,7.1

# **Step 3: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected BRCA1 target.**

**Inspect Missing Values**

In [19]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [20]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,6222842,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,4.6
1,None,None,6222843,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
2,None,None,6222844,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,52.8
3,None,None,6222845,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,250.0
4,None,None,6222846,[],CHEMBL1785941,Inhibition of BRCA1 by fluorescence polarizati...,B,None,None,BAO_0000190,...,Homo sapiens,Breast cancer type 1 susceptibility protein,9606,None,None,IC50,uM,UO_0000065,None,15.0

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [21]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [22]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [23]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [24]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL1784774,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O...,4600.0,intermediate
1,CHEMBL1784771,CC(=O)N[C@@H](CCC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[...,250000.0,inactive
2,CHEMBL1784772,CC(=O)N[C@@H](CC(C(=O)O)C(=O)O)C(=O)N1CCC[C@H]...,52800.0,inactive
3,CHEMBL1784773,CC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)...,250000.0,inactive
4,CHEMBL1784704,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N[C@@H](C)C(=O)...,15000.0,inactive

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [25]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL1784774,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N1CCC[C@H]1C(=O...,4600.0,intermediate
1,CHEMBL1784771,CC(=O)N[C@@H](CCC(=O)O)C(=O)N1CCC[C@H]1C(=O)N[...,250000.0,inactive
2,CHEMBL1784772,CC(=O)N[C@@H](CC(C(=O)O)C(=O)O)C(=O)N1CCC[C@H]...,52800.0,inactive
3,CHEMBL1784773,CC(=O)N[C@H](C(=O)N1CCC[C@H]1C(=O)N[C@H](C(=O)...,250000.0,inactive
4,CHEMBL1784704,CC(=O)N[C@@H](COP(=O)(O)O)C(=O)N[C@@H](C)C(=O)...,15000.0,inactive

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [26]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

cp: cannot create regular file '/content/gdrive/My Drive/Colab Notebooks/data': No such file or directory
ls: cannot access '/content/gdrive/My Drive/Colab Notebooks/data': No such file or directory

## **Results and Conclusion**

Bioactivity data for the BRCA1 target were successfully retrieved from the ChEMBL database and curated using standard QSAR preprocessing steps. A total of five IC50 bioactivity records were obtained and standardized for analysis.

Although the limited dataset size restricts the development of a statistically robust QSAR model, this exercise demonstrates the complete workflow for target evaluation, bioactivity data retrieval, and preprocessing. The curated dataset can serve as a proof-of-concept for QSAR methodology and highlights the importance of data availability and quality in target selection.